"""SentinelNet — in-house function-similarity threat intel.

For every scan, we take the decompiled C source of each reviewed function,
normalize it (strip Ghidra's autogenerated names + addresses + comments),
compute a MinHash signature, and store it tagged with the file's final verdict
and the AI's malware classification.

When a new scan happens, every decompiled function gets compared against the
corpus before Claude reasons over it — matches in known-malicious samples
become a meta-signal Claude sees in its prompt.

The longer you use Sentinel, the smarter it gets.

Storage lives at ~/.sentinel/sentinelnet.db so it survives venv rebuilds and
isn't tied to the project tree.
"""
from __future__ import annotations

import json
import os
import pickle
import re
import sqlite3
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Iterable

from datasketch import MinHash

# --------------------------------------------------------------------------
# Configuration
# --------------------------------------------------------------------------

DB_PATH = Path(os.environ.get("SENTINELNET_DB",
                              str(Path.home() / ".sentinel" / "sentinelnet.db")))
NUM_PERM = 128            # MinHash permutations (128 = good accuracy/speed)
SHINGLE_SIZE = 5          # token n-gram size for shingling
MIN_TOKENS_TO_STORE = 8   # functions shorter than this are noise (one-line wrappers)
DEFAULT_SIMILARITY = 0.50 # Jaccard threshold for "match"
TOP_K_DEFAULT = 5


# --------------------------------------------------------------------------
# Normalization
# --------------------------------------------------------------------------
# Ghidra's decompiled C is full of autogenerated names that vary between
# binaries even when the logic is identical. We strip those to leave only the
# structural shape: control flow keywords, API names, constants, types.

_GHIDRA_AUTO_NAMES = re.compile(
    r"\b("
    r"FUN_[0-9a-fA-F]+|"             # functions
    r"DAT_[0-9a-fA-F]+|"             # data
    r"PTR_[0-9a-fA-F]+|"             # pointers
    r"LAB_[0-9a-fA-F]+|"             # labels
    r"UNK_[0-9a-fA-F]+|"             # unknowns
    r"thunk_FUN_[0-9a-fA-F]+|"
    r"_DAT_[0-9a-fA-F]+|"
    r"local_[0-9a-fA-F]+|"           # locals
    r"param_[0-9]+|"                 # params
    r"[ui]Var[0-9]+|"                # uVar1, iVar2 etc.
    r"[ud]Var[0-9]+|"
    r"[ab-z]Var[0-9]+|"              # aVar, bVar etc.
    r"in_stack_[0-9a-fA-F]+|"
    r"unaff_[A-Z0-9]+|"
    r"extraout_[A-Z0-9_]+|"
    r"auVar[0-9]+|"
    r"_param_[0-9]+|"
    r"in_[A-Z0-9]+"                  # in_RDI, in_RAX, etc.
    r")\b"
)
_HEX_LITERAL = re.compile(r"\b0x[0-9a-fA-F]+\b")
_DEC_LITERAL = re.compile(r"\b[0-9]+\b")
_BLOCK_COMMENT = re.compile(r"/\*.*?\*/", re.DOTALL)
_LINE_COMMENT = re.compile(r"//[^\n]*")
_WHITESPACE = re.compile(r"\s+")
_TOKEN = re.compile(r"[A-Za-z_][A-Za-z0-9_]*|[(){}\[\];,+\-*/%=<>!&|^~?:]+")


def normalize_c_source(src: str) -> str:
    """Strip Ghidra-isms so structurally identical functions hash the same."""
    if not src:
        return ""
    src = _BLOCK_COMMENT.sub(" ", src)
    src = _LINE_COMMENT.sub(" ", src)
    src = _GHIDRA_AUTO_NAMES.sub("V", src)         # all autogen names collapse to V
    src = _HEX_LITERAL.sub("HEX", src)
    src = _DEC_LITERAL.sub("N", src)
    src = _WHITESPACE.sub(" ", src).strip()
    return src


def tokenize(normalized: str) -> list[str]:
    return _TOKEN.findall(normalized)


def shingles(tokens: list[str], k: int = SHINGLE_SIZE) -> Iterable[bytes]:
    if len(tokens) < k:
        # Pad with the whole text so very short functions still get fingerprinted.
        yield " ".join(tokens).encode("utf-8")
        return
    for i in range(len(tokens) - k + 1):
        yield " ".join(tokens[i:i + k]).encode("utf-8")


def compute_minhash(src: str) -> MinHash | None:
    """Return None if the source is too short to be meaningful."""
    norm = normalize_c_source(src)
    toks = tokenize(norm)
    if len(toks) < MIN_TOKENS_TO_STORE:
        return None
    m = MinHash(num_perm=NUM_PERM)
    for sh in shingles(toks):
        m.update(sh)
    return m


# --------------------------------------------------------------------------
# Storage
# --------------------------------------------------------------------------

SCHEMA = """
CREATE TABLE IF NOT EXISTS functions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    file_sha256 TEXT NOT NULL,
    file_name TEXT NOT NULL,
    function_name TEXT NOT NULL,
    verdict TEXT NOT NULL,                 -- ALLOW | BLOCK
    malware_class TEXT,                    -- JSON array
    malware_family TEXT,
    capabilities TEXT,                     -- JSON array
    minhash BLOB NOT NULL,
    token_count INTEGER NOT NULL,
    observed_at INTEGER NOT NULL,
    UNIQUE(file_sha256, function_name)
);
CREATE INDEX IF NOT EXISTS idx_file_sha ON functions(file_sha256);
CREATE INDEX IF NOT EXISTS idx_verdict ON functions(verdict);
CREATE INDEX IF NOT EXISTS idx_family ON functions(malware_family);
"""


def _connect() -> sqlite3.Connection:
    DB_PATH.parent.mkdir(parents=True, exist_ok=True)
    conn = sqlite3.connect(str(DB_PATH))
    conn.executescript(SCHEMA)
    return conn


# --------------------------------------------------------------------------
# Public API
# --------------------------------------------------------------------------

@dataclass
class Match:
    file_sha256: str
    file_name: str
    function_name: str
    verdict: str                    # ALLOW | BLOCK
    similarity: float               # Jaccard, 0..1
    malware_class: list[str] = field(default_factory=list)
    malware_family: str | None = None


@dataclass
class FunctionMatches:
    """All matches found for a single newly-scanned function."""
    function_name: str
    matches: list[Match] = field(default_factory=list)


def store_scan(
    *,
    file_sha256: str,
    file_name: str,
    verdict: str,                          # ALLOW or BLOCK
    decompiled: dict[str, str],            # function_name → C source
    malware_class: list[str] | None = None,
    malware_family: str | None = None,
    capabilities: list[str] | None = None,
) -> int:
    """Persist decompiled functions to the corpus. Returns # stored."""
    if not decompiled:
        return 0
    conn = _connect()
    stored = 0
    now = int(time.time())
    mc_json = json.dumps(malware_class or [])
    cap_json = json.dumps(capabilities or [])
    try:
        for fname, src in decompiled.items():
            mh = compute_minhash(src)
            if mh is None:
                continue
            blob = pickle.dumps(mh)
            try:
                conn.execute(
                    """
                    INSERT OR REPLACE INTO functions
                      (file_sha256, file_name, function_name, verdict,
                       malware_class, malware_family, capabilities,
                       minhash, token_count, observed_at)
                    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                    """,
                    (file_sha256, file_name, fname, verdict,
                     mc_json, malware_family, cap_json,
                     blob, len(tokenize(normalize_c_source(src))), now),
                )
                stored += 1
            except sqlite3.Error:
                continue
        conn.commit()
    finally:
        conn.close()
    return stored


def query_function(
    src: str,
    *,
    top_k: int = TOP_K_DEFAULT,
    threshold: float = DEFAULT_SIMILARITY,
    exclude_sha256: str | None = None,
) -> list[Match]:
    """Find the top-K most similar functions in the corpus.

    Brute-force Jaccard over MinHash signatures — fast enough for the
    thousands-of-functions scale; swap to MinHashLSH if/when the DB grows.
    """
    mh = compute_minhash(src)
    if mh is None:
        return []
    conn = _connect()
    try:
        rows = conn.execute(
            """
            SELECT file_sha256, file_name, function_name, verdict,
                   malware_class, malware_family, minhash
              FROM functions
             WHERE file_sha256 != COALESCE(?, '')
            """,
            (exclude_sha256 or "",),
        ).fetchall()
    finally:
        conn.close()

    results: list[Match] = []
    for sha, fname, func, verdict, mc_json, family, blob in rows:
        try:
            other = pickle.loads(blob)
        except Exception:
            continue
        try:
            sim = mh.jaccard(other)
        except Exception:
            continue
        if sim < threshold:
            continue
        try:
            mc = json.loads(mc_json) if mc_json else []
        except Exception:
            mc = []
        results.append(Match(
            file_sha256=sha,
            file_name=fname,
            function_name=func,
            verdict=verdict,
            similarity=sim,
            malware_class=mc,
            malware_family=family,
        ))
    results.sort(key=lambda m: -m.similarity)
    return results[:top_k]


def query_scan(
    decompiled: dict[str, str],
    *,
    exclude_sha256: str | None = None,
    top_k: int = TOP_K_DEFAULT,
    threshold: float = DEFAULT_SIMILARITY,
) -> list[FunctionMatches]:
    """Run query_function on every decompiled function in a scan."""
    out: list[FunctionMatches] = []
    for fname, src in decompiled.items():
        matches = query_function(
            src,
            top_k=top_k,
            threshold=threshold,
            exclude_sha256=exclude_sha256,
        )
        out.append(FunctionMatches(function_name=fname, matches=matches))
    return out


def stats() -> dict:
    """Return corpus stats for the daemon /sentinelnet/stats endpoint."""
    conn = _connect()
    try:
        total_funcs = conn.execute("SELECT COUNT(*) FROM functions").fetchone()[0]
        unique_files = conn.execute(
            "SELECT COUNT(DISTINCT file_sha256) FROM functions"
        ).fetchone()[0]
        by_verdict = dict(conn.execute(
            "SELECT verdict, COUNT(*) FROM functions GROUP BY verdict"
        ).fetchall())
        top_families = conn.execute(
            """
            SELECT malware_family, COUNT(DISTINCT file_sha256) AS n
              FROM functions
             WHERE malware_family IS NOT NULL AND malware_family != ''
             GROUP BY malware_family
             ORDER BY n DESC
             LIMIT 10
            """
        ).fetchall()
    finally:
        conn.close()
    return {
        "total_functions": total_funcs,
        "unique_files": unique_files,
        "by_verdict": by_verdict,
        "top_families": [{"family": f, "samples": n} for f, n in top_families],
        "db_path": str(DB_PATH),
    }


def related_files(file_sha256: str, limit: int = 10) -> list[dict]:
    """For a given file, return other files sharing similar functions."""
    conn = _connect()
    try:
        rows = conn.execute(
            "SELECT function_name, minhash FROM functions WHERE file_sha256 = ?",
            (file_sha256,),
        ).fetchall()
    finally:
        conn.close()
    if not rows:
        return []

    aggregate: dict[str, dict] = {}
    for _fname, blob in rows:
        try:
            mh = pickle.loads(blob)
        except Exception:
            continue
        for m in _query_minhash(mh, exclude_sha256=file_sha256, top_k=limit, threshold=DEFAULT_SIMILARITY):
            entry = aggregate.setdefault(m.file_sha256, {
                "file_sha256": m.file_sha256,
                "file_name": m.file_name,
                "verdict": m.verdict,
                "malware_family": m.malware_family,
                "shared_functions": 0,
                "max_similarity": 0.0,
            })
            entry["shared_functions"] += 1
            if m.similarity > entry["max_similarity"]:
                entry["max_similarity"] = m.similarity

    out = sorted(aggregate.values(),
                 key=lambda r: (-r["shared_functions"], -r["max_similarity"]))
    return out[:limit]


def _query_minhash(mh: MinHash, *, exclude_sha256: str | None, top_k: int, threshold: float) -> list[Match]:
    """Internal: query a pre-built MinHash."""
    conn = _connect()
    try:
        rows = conn.execute(
            """
            SELECT file_sha256, file_name, function_name, verdict,
                   malware_class, malware_family, minhash
              FROM functions
             WHERE file_sha256 != COALESCE(?, '')
            """,
            (exclude_sha256 or "",),
        ).fetchall()
    finally:
        conn.close()
    results: list[Match] = []
    for sha, fname, func, verdict, mc_json, family, blob in rows:
        try:
            other = pickle.loads(blob)
        except Exception:
            continue
        try:
            sim = mh.jaccard(other)
        except Exception:
            continue
        if sim < threshold:
            continue
        try:
            mc = json.loads(mc_json) if mc_json else []
        except Exception:
            mc = []
        results.append(Match(
            file_sha256=sha, file_name=fname, function_name=func,
            verdict=verdict, similarity=sim,
            malware_class=mc, malware_family=family,
        ))
    results.sort(key=lambda m: -m.similarity)
    return results[:top_k]
